### ISSUE TITLE
Missing requirements file

### ISSUE THREAD

**Issue by Moohmmd** [AmireNoori/MathCaptchaSolver#1]
hey amir, nice job with your work , you just forgot the requirements.txt in source, i`m kinda having problem here , it may caused by requirements installed version.

the error : 
while loading with TFVisionEncoderDecoderModel, an error is thrown:
Traceback (most recent call last):
  File "C:\Users\Mohmd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\pipelines\base.py", line 278, in infer_framework_load_model
    model = model_class.from_pretrained(model, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mohmd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\modeling_tf_utils.py", line 2902, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mohmd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\models\vision_encoder_decoder\modeling_tf_vision_encoder_decoder.py", line 219, in __init__
    decoder = TFAutoModelForCausalLM.from_config(config.decoder, name="decoder")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mohmd\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\transformers\models\auto\auto_factory.py", line 443, in from_config
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers.models.trocr.configuration_trocr.TrOCRConfig'> for this kind of AutoModel: TFAutoModelForCausalLM.
Model type should be one of BertConfig, CamembertConfig, CTRLConfig, GPT2Config, GPT2Config, GPTJConfig, OpenAIGPTConfig, OPTConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoFormerConfig, TransfoXLConfig, XGLMConfig, XLMConfig, XLMRobertaConfig, XLNetConfig.

\/\thanks again\/\

**Comment by AmireNoori** [comment]
Hello, dear Mohammad, I am very happy that you found my tool interesting.❤️
Thank you very much for reminding me of the requirements.txt file, I
uploaded it to GitHub a few minutes ago.
Regarding the error you encountered, it is related to the
TFAutoModelForCausalLM class in the transformers library.
If you already have this library installed in Python, I suggest that you
first make sure that you are using the latest version of transformers. You
can update this library to the latest version with the following command:

pip install --upgrade transformers

If you still encounter this error, I suggest you install the version of the
libraries that we currently use for the tool.
These versions are: transformers==4.36.2, opencv-python==4.8.0.74, numpy.
The versions of the libraries that are in the requirements.txt file are
similar to the versions that I introduced to you.

If you still have this error, send us an email, we will be happy to help
you again and try to solve your problem with new instructions.🤝

**Comment by niazkhoy** [comment]
hello please help me in solve captcha ve.cbi.ir

**Comment by niazkhoy** [comment]
thanks my dear
i solve cpatcha ve.cbi.ir in persian language 
![1](https://github.com/AmireNoori/MathCaptchaSolver/assets/27726125/a61c549f-7056-459e-a5ab-559f2376129b)
